fix bug:
~/bin/find-missing-commits.py . us/master ci -p tools/  -x
Traceback (most recent call last):
  File "/home/sglass/bin/find-missing-commits.py", line 172, in <module>
    main()
  File "/home/sglass/bin/find-missing-commits.py", line 166, in main
    missing_commits = find_missing_commits(repo_path, source_branch_name, target_branch_name, directory_path, exclude_matching_subjects)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sglass/bin/find-missing-commits.py", line 106, in find_missing_commits
    target_subjects.add(commit.message.splitlines()[0])
                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range